[package]
name = "minigrep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
rand = "0.9.1"
regex = "1.11.1"
thiserror = "2.0.12"
